# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.configuration-cache=true
# 禁用 toolchain 自动下载（使用本地 JDK）
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.auto-detect=true
